[package]
name = "nss-jsonfile"
version = "0.2.0"
authors = ["takonomura"]
edition = "2021"
repository = "https://github.com/takonomura/nss-jsonfile"
license = "LGPL-3.0"

[lib]
name = "nss_jsonfile"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.139"
# Use master branch to use initgroups features
libnss = { git = "https://github.com/csnewman/libnss-rs" }
paste = "1.0.12"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
