[package]
name = "nss-jsonfile"
version = "0.1.0"
authors = ["takonomura"]
edition = "2021"
repository = "https://github.com/takonomura/nss-jsonfile"

[lib]
name = "nss_jsonfile"
crate-type = ["cdylib"]

[dependencies]
