[package]
name = "nss-jsonfile"
version = "0.1.0"
authors = ["takonomura"]
edition = "2021"
repository = "https://github.com/takonomura/nss-jsonfile"

[lib]
name = "nss_jsonfile"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.137"
# Use master branch to use initgroups features
libnss = { git = "https://github.com/csnewman/libnss-rs" }
paste = "1.0.11"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
