name: CI

on:
  push:
    branches: [master]
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # renovate: tag=v3.3.0

      - name: Setup Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@869a4299cf8ac7db4ebffaec36ad82a682f88acb # renovate: tag=v2.0.1
        with:
          version: 0.10.1 # renovate: zig-version

      - name: Install cargo-zigbuild
        run: |
          CARGO_ZIGBUILD_VERSION=v0.16.2
          curl -sSLO "https://github.com/rust-cross/cargo-zigbuild/releases/download/${CARGO_ZIGBUILD_VERSION}/cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"
          tar xf "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz" cargo-zigbuild
          mv cargo-zigbuild /usr/local/bin/
          rm "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"

      - name: Build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # renovate: tag=v1.0.3
        with:
          command: zigbuild
          args: --target x86_64-unknown-linux-gnu.2.17 --release

      - name: Upload binary artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # renovate: tag=v3.1.2
        with:
          path: target/x86_64-unknown-linux-gnu/release/libnss_jsonfile.so
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # renovate: tag=v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/x86_64-unknown-linux-gnu/release/libnss_jsonfile.so
