name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Rust
        run: rustup show

      - name: Setup Zig
        run: |
          set -euo pipefail

          ZIG_VERSION=0.16.0
          ZIG_SHA256=70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00
          ZIG_ARCHIVE="zig-x86_64-linux-${ZIG_VERSION}.tar.xz"
          ZIG_URL="https://ziglang.org/download/${ZIG_VERSION}/${ZIG_ARCHIVE}"
          ZIG_DIR="${RUNNER_TEMP}/zig"
          curl -fsSLo "${RUNNER_TEMP}/${ZIG_ARCHIVE}" "${ZIG_URL}"
          echo "${ZIG_SHA256}  ${RUNNER_TEMP}/${ZIG_ARCHIVE}" | sha256sum -c -
          mkdir -p "${ZIG_DIR}"
          tar -xJf "${RUNNER_TEMP}/${ZIG_ARCHIVE}" -C "${ZIG_DIR}" --strip-components=1
          echo "${ZIG_DIR}" >> "${GITHUB_PATH}"
          "${ZIG_DIR}/zig" version

      - name: Install cargo-zigbuild
        run: |
          CARGO_ZIGBUILD_VERSION=0.23.0
          cargo install --locked --version "${CARGO_ZIGBUILD_VERSION}" cargo-zigbuild

      - name: Build
        run: cargo zigbuild --target x86_64-unknown-linux-gnu.2.17 --release

      - name: Build (aarch64)
        run: cargo zigbuild --target aarch64-unknown-linux-gnu.2.17 --release

      - name: Rename aarch64 artifact
        run: |
          mv target/aarch64-unknown-linux-gnu/release/libnss_jsonfile{,-aarch64}.so

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --verify-tag \
            --draft \
            --generate-notes \
            --title "${GITHUB_REF_NAME}" \
            target/x86_64-unknown-linux-gnu/release/libnss_jsonfile.so \
            target/aarch64-unknown-linux-gnu/release/libnss_jsonfile-aarch64.so
