name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Rust
        run: rustup show

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
        with:
          version: 0.13.0 # renovate: zig-version

      - name: Install cargo-zigbuild
        run: |
          CARGO_ZIGBUILD_VERSION=v0.19.5
          curl -sSLO "https://github.com/rust-cross/cargo-zigbuild/releases/download/${CARGO_ZIGBUILD_VERSION}/cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"
          tar xf "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz" cargo-zigbuild
          mv cargo-zigbuild /usr/local/bin/
          rm "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"

      - name: Build
        run: cargo zigbuild --target x86_64-unknown-linux-gnu.2.17 --release

      - name: Build (aarch64)
        run: cargo zigbuild --target aarch64-unknown-linux-gnu.2.17 --release

      - name: Rename aarch64 artifact
        run: |
          mv target/aarch64-unknown-linux-gnu/release/libnss_jsonfile{,-aarch64}.so

      - name: Release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/libnss_jsonfile.so
            target/aarch64-unknown-linux-gnu/release/libnss_jsonfile-aarch64.so
