name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Rust
        run: rustup show

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@7ab2955eb728f5440978d5824358023be3a2802d # v2.2.0
        with:
          version: 0.13.0 # renovate: zig-version

      - name: Install cargo-zigbuild
        run: |
          CARGO_ZIGBUILD_VERSION=v0.19.3
          curl -sSLO "https://github.com/rust-cross/cargo-zigbuild/releases/download/${CARGO_ZIGBUILD_VERSION}/cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"
          tar xf "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz" cargo-zigbuild
          mv cargo-zigbuild /usr/local/bin/
          rm "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"

      - name: Build
        run: cargo zigbuild --target x86_64-unknown-linux-gnu.2.17 --release

      - name: Build (aarch64)
        run: cargo zigbuild --target aarch64-unknown-linux-gnu.2.17 --release

      - name: Rename aarch64 artifact
        run: |
          mv target/aarch64-unknown-linux-gnu/release/libnss_jsonfile{,-aarch64}.so

      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/libnss_jsonfile.so
            target/aarch64-unknown-linux-gnu/release/libnss_jsonfile-aarch64.so
