name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          target: aarch64-unknown-linux-gnu

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@7ab2955eb728f5440978d5824358023be3a2802d # v2.2.0
        with:
          version: 0.12.0 # renovate: zig-version

      - name: Install cargo-zigbuild
        run: |
          CARGO_ZIGBUILD_VERSION=v0.18.3
          curl -sSLO "https://github.com/rust-cross/cargo-zigbuild/releases/download/${CARGO_ZIGBUILD_VERSION}/cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"
          tar xf "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz" cargo-zigbuild
          mv cargo-zigbuild /usr/local/bin/
          rm "cargo-zigbuild-${CARGO_ZIGBUILD_VERSION}.x86_64-unknown-linux-musl.tar.gz"

      - name: Build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: zigbuild
          args: --target x86_64-unknown-linux-gnu.2.17 --release

      - name: Build (aarch64)
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: zigbuild
          args: --target aarch64-unknown-linux-gnu.2.17 --release

      - name: Rename aarch64 artifact
        run: |
          mv target/aarch64-unknown-linux-gnu/release/libnss_jsonfile{,-aarch64}.so

      - name: Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/libnss_jsonfile.so
            target/aarch64-unknown-linux-gnu/release/libnss_jsonfile-aarch64.so
